name: SpaceStation

options:
  bundleIdPrefix: com.nsintegermax.spacestation

packages:
  AXSwift:
    url: https://github.com/tmandry/AXSwift
    from: 0.3.2
  PromiseKit:
    url: https://github.com/mxcl/PromiseKit
    from: 6.13.3

targets:
  SpaceStation:
    type: application
    platform: macOS
    deploymentTarget: 14.0
    sources:
      - path: Sources
    dependencies:
      - package: AXSwift
      - package: PromiseKit
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: SpaceStation
        NSMainStoryboardFile: ""
    settings:
      base:
        DEVELOPMENT_TEAM: QXZJBK5KC8
        CODE_SIGN_STYLE: Automatic
        ENABLE_APP_SANDBOX: NO
