name: SpaceStation

options:
  bundleIdPrefix: com.nsintegermax.spacestation

packages:
  AXSwift:
    url: https://github.com/tmandry/AXSwift
    from: 0.3.2
  OpenMultitouchSupport:
    url: https://github.com/Kyome22/OpenMultitouchSupport
    from: 3.0.3
  PromiseKit:
    url: https://github.com/mxcl/PromiseKit
    from: 6.13.3
  Swindler:
    url: https://github.com/tmandry/Swindler
    branch: main

targets:
  SpaceStation:
    type: application
    platform: macOS
    deploymentTarget: 14.0
    sources:
      - path: Sources
        excludes:
          - "main.swift"
    dependencies:
      - package: AXSwift
      - package: OpenMultitouchSupport
      - package: PromiseKit
      - package: Swindler
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: SpaceStation
        NSMainStoryboardFile: ""
        LSUIElement: true
    settings:
      base:
        DEVELOPMENT_TEAM: QXZJBK5KC8
        CODE_SIGN_STYLE: Automatic
        ENABLE_APP_SANDBOX: NO
